import { NextRequest, NextResponse } from 'next/server'
import { validateAuth } from '@/lib/api-auth'
import { supabase } from '@/lib/supabase'

/**
 * GET /api/agents/insights
 * Returns recent insights generated by all agents
 */
export async function GET(request: NextRequest) {
  const authResult = await validateAuth(request)
  if (!authResult.success || !authResult.user) {
    return NextResponse.json(
      { error: authResult.error || 'Authentication required' },
      { status: 401 }
    )
  }

  try {
    const businessId = authResult.user.businessId
    const { searchParams } = new URL(request.url)
    const limit = parseInt(searchParams.get('limit') || '20')
    const type = searchParams.get('type') // opportunity, risk, trend, anomaly, recommendation
    const agentId = searchParams.get('agentId')

    // Get recent agent executions with insights
    let query = supabase
      .from('agent_executions')
      .select('*')
      .eq('business_id', businessId)
      .not('result', 'is', null)
      .order('created_at', { ascending: false })
      .limit(limit * 2) // Fetch more since we'll filter

    if (agentId) {
      query = query.eq('agent_id', agentId)
    }

    const { data: executions, error } = await query

    if (error) {
      console.error('Error fetching executions:', error)
      return NextResponse.json(
        { error: 'Failed to fetch insights' },
        { status: 500 }
      )
    }

    // Extract and flatten insights from executions
    const insights: any[] = []
    for (const exec of executions || []) {
      const result = exec.result as any
      if (result?.insights && Array.isArray(result.insights)) {
        for (const insight of result.insights) {
          // Filter by type if specified
          if (type && insight.type !== type) continue

          insights.push({
            id: `${exec.id}_${insights.length}`,
            ...insight,
            agentId: exec.agent_id,
            executionId: exec.id,
            createdAt: exec.created_at,
          })

          if (insights.length >= limit) break
        }
      }
      if (insights.length >= limit) break
    }

    // Get insight summary by type
    const summary = {
      opportunities: insights.filter((i) => i.type === 'opportunity').length,
      risks: insights.filter((i) => i.type === 'risk').length,
      trends: insights.filter((i) => i.type === 'trend').length,
      anomalies: insights.filter((i) => i.type === 'anomaly').length,
      recommendations: insights.filter((i) => i.type === 'recommendation').length,
    }

    // Get high-impact insights
    const highImpact = insights.filter((i) => i.impact === 'high').slice(0, 5)

    return NextResponse.json({
      insights,
      summary,
      highImpact,
      total: insights.length,
    })
  } catch (error) {
    console.error('Error getting insights:', error)
    return NextResponse.json(
      { error: 'Failed to get insights' },
      { status: 500 }
    )
  }
}
