/**
 * VoiceFly AI Agent System - Type Definitions
 *
 * This module defines the core types for the Maya Prime agent orchestration system.
 */

// Agent execution status
export type AgentStatus = 'idle' | 'running' | 'completed' | 'failed' | 'queued'

// Priority levels for agent tasks
export type AgentPriority = 'critical' | 'high' | 'medium' | 'low'

// Agent categories (clusters)
export type AgentCluster =
  | 'revenue'
  | 'customer'
  | 'operations'
  | 'marketing'
  | 'compliance'
  | 'system'
  | 'competitive'
  | 'financial'
  | 'product'

// Base agent configuration
export interface AgentConfig {
  id: string
  name: string
  description: string
  cluster: AgentCluster
  enabled: boolean
  schedule?: AgentSchedule
  triggers?: AgentTrigger[]
  dependencies?: string[] // IDs of agents that must complete first
}

// Scheduling configuration for periodic agents
export interface AgentSchedule {
  type: 'cron' | 'interval' | 'daily' | 'weekly' | 'monthly'
  value: string // cron expression or interval in ms
  timezone?: string
  lastRun?: Date
  nextRun?: Date
}

// Event triggers for reactive agents
export interface AgentTrigger {
  event: string
  conditions?: Record<string, any>
  debounceMs?: number
}

// Agent execution context
export interface AgentContext {
  businessId: string
  userId?: string
  triggeredBy: 'schedule' | 'event' | 'manual' | 'orchestrator'
  triggerData?: any
  parentExecutionId?: string
  startTime: Date
  metadata?: Record<string, any>
}

// Agent execution result
export interface AgentResult {
  success: boolean
  executionId: string
  agentId: string
  businessId: string
  duration: number // ms
  output?: any
  error?: string
  insights?: AgentInsight[]
  actions?: AgentAction[]
  alerts?: AgentAlert[]
  nextSteps?: string[]
}

// Insights generated by agents
export interface AgentInsight {
  type: 'opportunity' | 'risk' | 'trend' | 'anomaly' | 'recommendation'
  title: string
  description: string
  confidence: number // 0-1
  impact: 'high' | 'medium' | 'low'
  data?: Record<string, any>
  suggestedActions?: string[]
}

// Actions that agents can queue
export interface AgentAction {
  type: string
  target: string
  payload: any
  priority: AgentPriority
  scheduledFor?: Date
  requiresApproval?: boolean
}

// Alerts generated by agents
export interface AgentAlert {
  severity: 'critical' | 'warning' | 'info'
  title: string
  message: string
  category: string
  timestamp: Date
  acknowledged?: boolean
  metadata?: Record<string, any>
}

// Business health metrics tracked by Maya Prime
export interface BusinessHealthMetrics {
  overall: number // 0-100 score
  revenue: HealthDimension
  customer: HealthDimension
  operations: HealthDimension
  compliance: HealthDimension
  system: HealthDimension
  lastUpdated: Date
}

export interface HealthDimension {
  score: number // 0-100
  trend: 'improving' | 'stable' | 'declining'
  alerts: number
  topIssue?: string
}

// Daily summary generated by Maya Prime
export interface DailySummary {
  businessId: string
  date: Date
  metrics: {
    totalCalls: number
    totalRevenue: number
    appointmentsBooked: number
    leadsGenerated: number
    conversionRate: number
    customerSatisfaction: number
  }
  highlights: string[]
  concerns: string[]
  opportunities: AgentInsight[]
  recommendedActions: AgentAction[]
  agentExecutions: {
    total: number
    successful: number
    failed: number
    insights: number
    actions: number
  }
}

// Call intelligence types
export interface CallAnalysis {
  callId: string
  businessId: string
  duration: number
  outcome: CallOutcome
  sentiment: CallSentiment
  intentDetected: string[]
  keyTopics: string[]
  appointmentBooked: boolean
  leadQuality: 'hot' | 'warm' | 'cold'
  followUpRequired: boolean
  suggestedFollowUp?: string
  transcriptSummary?: string
  coachingOpportunities?: string[]
}

export type CallOutcome =
  | 'appointment_booked'
  | 'callback_scheduled'
  | 'information_provided'
  | 'voicemail_left'
  | 'no_answer'
  | 'customer_declined'
  | 'transferred'
  | 'other'

export interface CallSentiment {
  overall: 'positive' | 'neutral' | 'negative'
  score: number // -1 to 1
  customerFrustration: boolean
  urgencyLevel: 'high' | 'medium' | 'low'
}

// Lead qualification types
export interface LeadQualification {
  leadId: string
  businessId: string
  score: number // 0-100
  tier: 'hot' | 'warm' | 'cold' | 'disqualified'
  factors: QualificationFactor[]
  recommendedAction: string
  urgency: 'immediate' | 'within_24h' | 'within_week' | 'nurture'
  estimatedValue?: number
}

export interface QualificationFactor {
  name: string
  weight: number
  score: number
  notes?: string
}

// Agent message for inter-agent communication
export interface AgentMessage {
  from: string
  to: string
  type: 'request' | 'response' | 'notification' | 'alert'
  payload: any
  timestamp: Date
  correlationId?: string
}

// Orchestrator state
export interface OrchestratorState {
  isRunning: boolean
  lastHeartbeat: Date
  activeAgents: string[]
  queuedTasks: number
  health: BusinessHealthMetrics
  dailySummary?: DailySummary
}

// Event types for the agent system
export enum AgentEvent {
  // Call events
  CALL_STARTED = 'call.started',
  CALL_ENDED = 'call.ended',
  CALL_TRANSFERRED = 'call.transferred',

  // Lead events
  LEAD_CREATED = 'lead.created',
  LEAD_UPDATED = 'lead.updated',
  LEAD_CONVERTED = 'lead.converted',

  // Appointment events
  APPOINTMENT_BOOKED = 'appointment.booked',
  APPOINTMENT_CANCELLED = 'appointment.cancelled',
  APPOINTMENT_COMPLETED = 'appointment.completed',
  APPOINTMENT_NOSHOW = 'appointment.noshow',

  // Revenue events
  PAYMENT_RECEIVED = 'payment.received',
  SUBSCRIPTION_CHANGED = 'subscription.changed',
  CREDITS_LOW = 'credits.low',

  // System events
  HEALTH_CHECK = 'system.health_check',
  DAILY_SUMMARY = 'system.daily_summary',
  ERROR_THRESHOLD = 'system.error_threshold',

  // Marketing events
  CAMPAIGN_SENT = 'campaign.sent',
  CAMPAIGN_COMPLETED = 'campaign.completed',

  // Customer events
  CUSTOMER_FEEDBACK = 'customer.feedback',
  CHURN_RISK = 'customer.churn_risk',

  // Chat widget events
  CHAT_STARTED = 'chat.started',
  CHAT_ENDED = 'chat.ended',
}

// Credit cost for agent operations
export enum AgentCreditCost {
  CALL_ANALYSIS = 2,
  LEAD_QUALIFICATION = 3,
  DAILY_SUMMARY = 5,
  DEEP_ANALYSIS = 10,
  COMPETITIVE_RESEARCH = 15,
}

// Chain definition — what one agent's result triggers next
export interface AgentChain {
  sourceAgentId: string
  condition: (result: AgentResult) => boolean
  targetAgentId: string
  extractData: (result: AgentResult) => any // maps source output to target agent input
  priority: AgentPriority
}
