-- Agent System Tables
-- Creates the 3 tables required by Maya Prime and the agent registry:
-- agent_alerts, agent_executions, daily_summaries

-- ============================================================
-- agent_alerts
-- Stores alerts generated by Maya Prime (business-level and
-- platform-level). business_id is TEXT (not UUID FK) so we
-- can store the 'platform' sentinel for admin-level alerts.
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_alerts (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id TEXT        NOT NULL,
  severity    TEXT        NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  title       TEXT        NOT NULL,
  message     TEXT        NOT NULL,
  category    TEXT        NOT NULL,
  metadata    JSONB,
  acknowledged BOOLEAN    NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_alerts_business ON agent_alerts (business_id);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_severity ON agent_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_created  ON agent_alerts (created_at DESC);

ALTER TABLE agent_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS agent_alerts_service_bypass ON agent_alerts;
CREATE POLICY agent_alerts_service_bypass ON agent_alerts
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================
-- agent_executions
-- Log of every agent run — success or failure, duration,
-- insight/action/alert counts. business_id is TEXT for
-- flexibility (some executions may be platform-level).
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_executions (
  id              TEXT        PRIMARY KEY,
  agent_id        TEXT        NOT NULL,
  business_id     TEXT        NOT NULL,
  status          TEXT        NOT NULL CHECK (status IN ('completed', 'failed')),
  duration_ms     INTEGER,
  insights_count  INTEGER     DEFAULT 0,
  actions_count   INTEGER     DEFAULT 0,
  alerts_count    INTEGER     DEFAULT 0,
  error           TEXT,
  result          JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_executions_business ON agent_executions (business_id);
CREATE INDEX IF NOT EXISTS idx_agent_executions_agent   ON agent_executions (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_executions_created ON agent_executions (created_at DESC);

ALTER TABLE agent_executions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS agent_executions_service_bypass ON agent_executions;
CREATE POLICY agent_executions_service_bypass ON agent_executions
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================
-- daily_summaries
-- One row per business per day — AI-generated summary of
-- calls, revenue, appointments, and agent activity.
-- ============================================================
CREATE TABLE IF NOT EXISTS daily_summaries (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id         TEXT        NOT NULL,
  date                DATE        NOT NULL,
  metrics             JSONB,
  highlights          TEXT[],
  concerns            TEXT[],
  opportunities       TEXT[],
  recommended_actions TEXT[],
  agent_executions    JSONB,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (business_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_summaries_business ON daily_summaries (business_id);
CREATE INDEX IF NOT EXISTS idx_daily_summaries_date     ON daily_summaries (date DESC);

ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS daily_summaries_service_bypass ON daily_summaries;
CREATE POLICY daily_summaries_service_bypass ON daily_summaries
  FOR ALL USING (auth.role() = 'service_role');
